package com.robothree.central.persistence.mybatis.schema;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

final class CentralSchemaSpecification {

    static final Map<String, List<RequiredColumn>> TABLES = tables();

    static final List<String> CONSTRAINTS = List.of(
            "enterprise_verified_identity_pkey",
            "ck_verified_identity_digest",
            "ck_verified_identity_expiry",
            "enterprise_user_permission_pkey",
            "enterprise_user_permission_revision_check",
            "enterprise_device_pkey",
            "enterprise_device_revision_check",
            "ck_device_public_key_digest",
            "ck_device_public_key_format",
            "ck_device_algorithm",
            "device_enrollment_grant_pkey",
            "device_enrollment_grant_code_digest_key",
            "ck_enrollment_code_digest",
            "ck_enrollment_expiry",
            "device_challenge_pkey",
            "device_challenge_verified_identity_id_fkey",
            "device_challenge_challenge_digest_key",
            "ck_challenge_digest",
            "ck_challenge_public_key_digest",
            "ck_challenge_expiry",
            "ck_challenge_algorithms_nonempty",
            "ck_challenge_consumption_complete",
            "uq_device_challenge_identity_pair",
            "access_token_issuance_pkey",
            "access_token_issuance_token_digest_key",
            "access_token_issuance_device_id_fkey",
            "access_token_issuance_device_revision_check",
            "access_token_issuance_permission_revision_check",
            "access_token_issuance_challenge_id_key",
            "access_token_issuance_challenge_id_fkey",
            "ck_token_digest",
            "ck_token_identity_digest",
            "ck_token_expiry",
            "enterprise_configuration_snapshot_pkey",
            "ck_configuration_revision",
            "ck_configuration_digest",
            "ck_configuration_document",
            "enterprise_package_document_pkey",
            "ck_package_kind",
            "ck_package_revision",
            "ck_package_digest",
            "ck_package_document",
            "model_invocation_pkey",
            "model_invocation_request_id_key",
            "uq_model_invocation_client_request",
            "ck_model_invocation_digests",
            "ck_model_invocation_status",
            "ck_model_invocation_revision",
            "ck_model_invocation_idle_timeout",
            "ck_model_invocation_admission",
            "ck_model_invocation_stream_digest",
            "ck_model_invocation_cancel_intent",
            "ck_model_invocation_usage",
            "ck_model_invocation_time_order",
            "model_invocation_event_pkey",
            "model_invocation_event_invocation_id_fkey",
            "uq_model_invocation_event_id",
            "ck_model_invocation_event_sequence",
            "ck_model_invocation_event_revision",
            "ck_model_invocation_event_status",
            "ck_model_invocation_event_digest",
            "ck_model_invocation_event_metadata",
            "model_invocation_recovery_lease_pkey",
            "model_invocation_recovery_lease_invocation_id_fkey",
            "model_invocation_recovery_lease_fencing_epoch_check",
            "model_invocation_recovery_lease_status_revision_check",
            "model_invocation_recovery_lease_recovery_attempt_check",
            "ck_model_invocation_lease_policy",
            "ck_model_invocation_lease_time",
            "model_invocation_audit_outbox_pkey",
            "model_invocation_audit_outbox_invocation_id_fkey",
            "model_invocation_audit_outbox_attempt_count_check",
            "uq_model_invocation_audit_event",
            "ck_model_invocation_audit_digest",
            "model_invocation_provider_attempt_pkey",
            "model_invocation_provider_attempt_authority_invocation_id_fkey",
            "model_invocation_provider_attempt_fencing_epoch_check",
            "uq_model_invocation_provider_attempt_epoch",
            "ck_model_invocation_provider_attempt_authority",
            "ck_model_invocation_provider_attempt_digest",
            "model_invocation_usage_fact_pkey",
            "model_invocation_usage_fact_fencing_epoch_check",
            "model_invocation_usage_fact_provider_input_tokens_check",
            "model_invocation_usage_fact_provider_output_tokens_check",
            "model_invocation_usage_fact_cache_read_input_tokens_check",
            "model_invocation_usage_fact_cache_write_input_tokens_check",
            "model_invocation_usage_fact_reasoning_output_tokens_check",
            "model_invocation_usage_fact_normalized_total_input_tokens_check",
            "uq_model_invocation_usage_attempt",
            "fk_model_invocation_usage_attempt",
            "ck_model_invocation_usage_authority",
            "ck_model_invocation_usage_digests",
            "ck_model_invocation_usage_protocol",
            "ck_model_invocation_usage_disposition",
            "ck_model_invocation_usage_reasoning_subset",
            "model_invocation_cache_context_pkey",
            "model_invocation_cache_context_invocation_id_fkey",
            "ck_model_invocation_cache_context_authority",
            "ck_model_invocation_cache_context_contract",
            "ck_model_invocation_cache_context_digests",
            "model_invocation_prompt_cache_plan_pkey",
            "model_invocation_prompt_cache_plan_invocation_id_fkey",
            "ck_prompt_cache_plan_digests",
            "ck_prompt_cache_plan_projection_mode",
            "ck_prompt_cache_plan_skip_reason",
            "ck_prompt_cache_plan_eligibility",
            "ck_prompt_cache_plan_key_mode",
            "enterprise_session_challenge_binding_pkey",
            "fk_enterprise_session_challenge_identity",
            "uq_enterprise_session_challenge_correlation",
            "uq_enterprise_session_challenge_binding_digest",
            "uq_enterprise_session_challenge_binding_identity",
            "ck_enterprise_session_challenge_profile",
            "ck_enterprise_session_challenge_audience",
            "ck_enterprise_session_challenge_source",
            "ck_enterprise_session_challenge_device_key",
            "ck_enterprise_session_challenge_digests",
            "ck_enterprise_session_challenge_permissions",
            "enterprise_session_lease_issuance_pkey",
            "uq_enterprise_session_token_digest",
            "uq_enterprise_session_challenge_issuance",
            "fk_enterprise_session_lease_binding",
            "fk_enterprise_session_lease_identity",
            "fk_enterprise_session_lease_device",
            "ck_enterprise_session_lease_profile",
            "ck_enterprise_session_lease_audience",
            "ck_enterprise_session_lease_owner_lengths",
            "ck_enterprise_session_lease_status",
            "ck_enterprise_session_lease_time",
            "ck_enterprise_session_lease_source_revision",
            "ck_enterprise_session_lease_raw_digests",
            "ck_enterprise_session_lease_wire_digests",
            "ck_enterprise_session_lease_permissions",
            "ck_enterprise_session_lease_documents",
            "admin_model_revision_pkey",
            "ck_admin_model_revision_digest",
            "ck_admin_model_revision_document",
            "admin_model_head_pkey",
            "fk_admin_model_head_revision",
            "admin_model_default_pkey",
            "fk_admin_model_default_revision",
            "admin_model_credential_pkey",
            "ck_admin_model_credential_revision",
            "ck_admin_model_credential_ciphertext",
            "admin_model_gateway_binding_pkey",
            "ck_admin_model_gateway_binding_digests",
            "ck_admin_model_gateway_binding_document",
            "admin_model_command_receipt_pkey",
            "ck_admin_model_command_digest",
            "ck_admin_model_command_result",
            "admin_model_audit_pkey",
            "ck_admin_model_audit_revision",
            "ck_admin_model_audit_fields",
            "robothree_schema_version_pkey",
            "robothree_schema_version_script_name_key",
            "robothree_schema_version_version_check",
            "ck_robothree_schema_digest");

    static final List<String> INDEXES = List.of(
            "uq_verified_identity_digest",
            "ix_verified_identity_user",
            "ix_enterprise_user_permission_enabled",
            "uq_enterprise_device_key",
            "uq_enterprise_device_public_key",
            "ix_enterprise_device_status",
            "ix_enrollment_grant_owner",
            "ix_device_challenge_identity",
            "ix_device_challenge_pending",
            "ix_device_challenge_consumed_request",
            "ix_access_token_subject",
            "uq_configuration_snapshot_digest",
            "uq_configuration_single_active",
            "uq_configuration_etag",
            "uq_package_document_digest",
            "ix_model_invocation_subject_status",
            "ix_model_invocation_recovery",
            "ix_model_invocation_event_cursor",
            "ix_model_invocation_lease_expiry",
            "ix_model_invocation_audit_pending",
            "ix_model_invocation_provider_attempt_invocation",
            "ix_model_invocation_usage_fact_invocation",
            "ix_model_invocation_cache_context_scope",
            "ix_prompt_cache_plan_monotonicity",
            "ix_prompt_cache_plan_key",
            "ix_enterprise_session_challenge_identity_created",
            "ix_enterprise_session_lease_subject_expiry",
            "ix_enterprise_session_lease_source_decision",
            "ix_admin_model_revision_display",
            "ix_admin_model_credential_model",
            "ix_admin_model_audit_time");

    private CentralSchemaSpecification() {}

    private static Map<String, List<RequiredColumn>> tables() {
        Map<String, List<RequiredColumn>> tables = new LinkedHashMap<>();
        tables.put(
                "enterprise_verified_identity",
                List.of(
                        required("verified_identity_id", "uuid"),
                        required("enterprise_id", "varchar"),
                        required("user_id", "varchar"),
                        required("provider", "varchar"),
                        required("provider_subject_digest", "bpchar"),
                        required("identity_digest", "bpchar"),
                        required("issued_at", "timestamptz"),
                        required("expires_at", "timestamptz"),
                        nullable("disabled_at", "timestamptz")));
        tables.put(
                "enterprise_user_permission",
                List.of(
                        required("enterprise_id", "varchar"),
                        required("user_id", "varchar"),
                        required("permission", "varchar"),
                        required("enabled", "bool"),
                        required("revision", "int8"),
                        required("updated_at", "timestamptz")));
        tables.put(
                "enterprise_device",
                List.of(
                        required("device_id", "varchar"),
                        required("enterprise_id", "varchar"),
                        required("device_key_id", "varchar"),
                        required("public_key_format", "varchar"),
                        required("public_key_encoded", "text"),
                        required("public_key_digest", "bpchar"),
                        required("algorithm", "varchar"),
                        required("trust_source", "varchar"),
                        required("managed_status", "varchar"),
                        required("compliance_status", "varchar"),
                        required("revision", "int8"),
                        required("registered_at", "timestamptz"),
                        nullable("revoked_at", "timestamptz"),
                        nullable("disabled_at", "timestamptz")));
        tables.put(
                "device_enrollment_grant",
                List.of(
                        required("enrollment_grant_id", "uuid"),
                        required("code_digest", "bpchar"),
                        required("enterprise_id", "varchar"),
                        required("authorized_user_id", "varchar"),
                        required("issued_at", "timestamptz"),
                        required("expires_at", "timestamptz"),
                        nullable("consumed_at", "timestamptz"),
                        nullable("disabled_at", "timestamptz")));
        tables.put(
                "device_challenge",
                List.of(
                        required("challenge_id", "uuid"),
                        required("purpose", "varchar"),
                        required("verified_identity_id", "uuid"),
                        required("client_instance_id", "varchar"),
                        nullable("expected_device_key_id", "varchar"),
                        nullable("expected_public_key_digest", "bpchar"),
                        required("nonce", "varchar"),
                        required("audience", "varchar"),
                        required("allowed_algorithms", "_text"),
                        required("challenge_digest", "bpchar"),
                        required("issued_at", "timestamptz"),
                        required("expires_at", "timestamptz"),
                        nullable("consumed_at", "timestamptz"),
                        nullable("consumed_by", "varchar"),
                        nullable("consumed_request_digest", "bpchar")));
        tables.put(
                "access_token_issuance",
                List.of(
                        required("token_id", "uuid"),
                        required("token_digest", "bpchar"),
                        required("enterprise_id", "varchar"),
                        required("user_id", "varchar"),
                        required("device_id", "varchar"),
                        required("client_instance_id", "varchar"),
                        required("permissions", "_text"),
                        required("identity_digest", "bpchar"),
                        required("device_revision", "int8"),
                        required("permission_revision", "int8"),
                        required("issued_at", "timestamptz"),
                        required("expires_at", "timestamptz"),
                        required("challenge_id", "uuid")));
        tables.put(
                "enterprise_configuration_snapshot",
                List.of(
                        required("snapshot_id", "varchar"),
                        required("revision", "bpchar"),
                        required("digest", "bpchar"),
                        required("schema_version", "varchar"),
                        required("document_json", "text"),
                        required("etag", "varchar"),
                        required("active", "bool"),
                        required("generated_at", "timestamptz"),
                        required("inserted_at", "timestamptz")));
        tables.put(
                "enterprise_package_document",
                List.of(
                        required("package_id", "varchar"),
                        required("kind", "varchar"),
                        required("revision", "bpchar"),
                        required("digest", "bpchar"),
                        required("document_json", "text"),
                        required("inserted_at", "timestamptz")));
        tables.put(
                "model_invocation",
                List.of(
                        required("invocation_id", "uuid"),
                        required("enterprise_id", "varchar"),
                        required("user_id", "varchar"),
                        required("device_id", "varchar"),
                        required("client_instance_id", "varchar"),
                        required("client_request_id", "uuid"),
                        required("request_id", "uuid"),
                        required("request_digest", "bpchar"),
                        required("model_id", "varchar"),
                        required("model_revision", "bpchar"),
                        required("configuration_revision", "bpchar"),
                        required("runtime_registry_generation", "bpchar"),
                        required("admission_type", "varchar"),
                        required("admission_digest", "bpchar"),
                        required("provider_request_deadline_at", "timestamptz"),
                        required("provider_stream_idle_timeout_millis", "int8"),
                        required("status", "varchar"),
                        required("status_revision", "int8"),
                        required("last_durable_event_sequence", "int8"),
                        nullable("durable_event_stream_digest", "bpchar"),
                        nullable("dispatch_decision", "varchar"),
                        nullable("cancel_requested_at", "timestamptz"),
                        nullable("cancel_reason", "varchar"),
                        nullable("timeout_intent_at", "timestamptz"),
                        nullable("usage_json", "text"),
                        nullable("finish_reason", "varchar"),
                        nullable("safe_error_code", "varchar"),
                        nullable("safe_summary", "varchar"),
                        required("created_at", "timestamptz"),
                        nullable("started_at", "timestamptz"),
                        nullable("ended_at", "timestamptz"),
                        required("updated_at", "timestamptz")));
        tables.put(
                "model_invocation_event",
                List.of(
                        required("invocation_id", "uuid"),
                        required("event_sequence", "int8"),
                        required("event_id", "uuid"),
                        required("event_type", "varchar"),
                        nullable("status", "varchar"),
                        required("status_revision", "int8"),
                        required("event_digest", "bpchar"),
                        required("stream_digest", "bpchar"),
                        required("metadata_json", "text"),
                        required("created_at", "timestamptz")));
        tables.put(
                "model_invocation_recovery_lease",
                List.of(
                        required("invocation_id", "uuid"),
                        required("owner_node_id", "varchar"),
                        required("fencing_epoch", "int8"),
                        required("status_revision", "int8"),
                        required("lease_expires_at", "timestamptz"),
                        required("database_observed_at", "timestamptz"),
                        required("recovery_attempt", "int8"),
                        required("policy_revision", "bpchar"),
                        required("updated_at", "timestamptz")));
        tables.put(
                "model_invocation_audit_outbox",
                List.of(
                        required("outbox_id", "uuid"),
                        required("invocation_id", "uuid"),
                        required("event_id", "uuid"),
                        required("event_type", "varchar"),
                        required("event_digest", "bpchar"),
                        required("created_at", "timestamptz"),
                        nullable("published_at", "timestamptz"),
                        required("attempt_count", "int8")));
        tables.put(
                "model_invocation_provider_attempt",
                List.of(
                        required("usage_authority", "varchar"),
                        required("authority_invocation_id", "uuid"),
                        required("provider_attempt_key", "bpchar"),
                        required("fencing_epoch", "int8"),
                        required("registered_at", "timestamptz")));
        tables.put(
                "model_invocation_usage_fact",
                List.of(
                        required("usage_fact_id", "uuid"),
                        required("usage_authority", "varchar"),
                        required("authority_invocation_id", "uuid"),
                        required("provider_attempt_key", "bpchar"),
                        required("fencing_epoch", "int8"),
                        required("usage_digest", "bpchar"),
                        required("source_protocol", "varchar"),
                        required("reporting_semantics_revision", "bpchar"),
                        required("provider_input_tokens", "int8"),
                        required("provider_output_tokens", "int8"),
                        nullable("cache_read_input_tokens", "int8"),
                        nullable("cache_write_input_tokens", "int8"),
                        nullable("reasoning_output_tokens", "int8"),
                        required("normalized_total_input_tokens", "int8"),
                        required("attempt_disposition", "varchar"),
                        required("recorded_at", "timestamptz")));
        tables.put(
                "model_invocation_cache_context",
                List.of(
                        required("invocation_id", "uuid"),
                        required("cache_execution_authority", "varchar"),
                        required("gateway_contract_version", "varchar"),
                        required("session_scope_digest", "bpchar"),
                        required("cache_context_digest", "bpchar"),
                        required("context_record_digest", "bpchar"),
                        required("created_at", "timestamptz")));
        tables.put(
                "model_invocation_prompt_cache_plan",
                List.of(
                        required("invocation_id", "uuid"),
                        required("cache_context_digest", "bpchar"),
                        required("cache_scope_id_digest", "bpchar"),
                        required("static_source_lock_digest", "bpchar"),
                        required("static_prefix_digest", "bpchar"),
                        required("compatibility_fingerprint_digest", "bpchar"),
                        nullable("cache_key_digest", "bpchar"),
                        required("cache_policy_revision", "bpchar"),
                        required("binding_revision", "bpchar"),
                        required("binding_digest", "bpchar"),
                        required("profile_id", "varchar"),
                        required("profile_revision", "bpchar"),
                        required("profile_digest", "bpchar"),
                        required("provider_projection_mode", "varchar"),
                        required("eligible", "bool"),
                        nullable("skip_reason", "varchar"),
                        required("plan_digest", "bpchar"),
                        required("created_at", "timestamptz")));
        tables.put(
                "enterprise_session_challenge_binding",
                List.of(
                        required("challenge_id", "uuid"),
                        required("verified_identity_id", "uuid"),
                        required("claims_profile", "varchar"),
                        required("identity_source_revision", "varchar"),
                        required("current_client_instance_id", "uuid"),
                        required("audience", "varchar"),
                        required("required_permissions", "_text"),
                        required("device_key_id", "varchar"),
                        required("correlation_id", "uuid"),
                        required("binding_digest", "bpchar"),
                        required("record_digest", "bpchar"),
                        required("created_at", "timestamptz")));
        tables.put(
                "enterprise_session_lease_issuance",
                List.of(
                        required("token_id", "uuid"),
                        required("token_digest", "bpchar"),
                        required("claims_profile", "varchar"),
                        required("issuer", "varchar"),
                        required("audience", "varchar"),
                        required("enterprise_id", "varchar"),
                        required("user_id", "varchar"),
                        required("device_id", "varchar"),
                        required("verified_identity_id", "uuid"),
                        required("identity_source_revision", "varchar"),
                        required("client_instance_id", "uuid"),
                        required("permissions", "_text"),
                        required("identity_digest", "bpchar"),
                        required("device_source_revision", "int8"),
                        required("device_revision_digest", "varchar"),
                        required("permission_revision_digest", "varchar"),
                        required("compatibility_revision", "varchar"),
                        required("trust_source", "varchar"),
                        required("managed_status", "varchar"),
                        required("compliance_status", "varchar"),
                        required("issued_at", "timestamptz"),
                        required("expires_at", "timestamptz"),
                        required("trust_evaluated_at", "timestamptz"),
                        required("challenge_id", "uuid"),
                        required("challenge_binding_digest", "bpchar"),
                        required("session_assertion_revision", "varchar"),
                        required("session_assertion_digest", "varchar"),
                        required("session_assertion_json", "text"),
                        required("device_trust_decision_revision", "varchar"),
                        required("device_trust_decision_digest", "varchar"),
                        required("device_trust_decision_json", "text"),
                        required("source_decision_digest", "varchar"),
                        required("request_digest", "bpchar"),
                        required("record_digest", "bpchar")));
        tables.put(
                "admin_model_revision",
                List.of(
                        required("model_id", "varchar"),
                        required("model_revision", "varchar"),
                        required("display_name", "varchar"),
                        required("record_json", "text"),
                        required("record_digest", "bpchar"),
                        required("created_at", "timestamptz")));
        tables.put(
                "admin_model_head",
                List.of(
                        required("model_id", "varchar"),
                        required("model_revision", "varchar"),
                        required("updated_at", "timestamptz")));
        tables.put(
                "admin_model_default",
                List.of(
                        required("singleton", "bool"),
                        required("model_id", "varchar"),
                        required("model_revision", "varchar"),
                        required("updated_at", "timestamptz")));
        tables.put(
                "admin_model_credential",
                List.of(
                        required("credential_reference", "varchar"),
                        required("model_id", "varchar"),
                        required("credential_revision", "varchar"),
                        required("key_id", "varchar"),
                        required("nonce", "bytea"),
                        required("ciphertext", "bytea"),
                        required("created_at", "timestamptz")));
        tables.put(
                "admin_model_command_receipt",
                List.of(
                        required("command_id", "uuid"),
                        required("correlation_id", "uuid"),
                        required("command_digest", "varchar"),
                        required("result_json", "text"),
                        required("occurred_at", "timestamptz")));
        tables.put(
                "admin_model_gateway_binding",
                List.of(
                        required("decision_digest", "bpchar"),
                        required("binding_revision", "varchar"),
                        required("binding_digest", "varchar"),
                        required("binding_json", "text"),
                        required("created_at", "timestamptz")));
        tables.put(
                "admin_model_audit",
                List.of(
                        required("event_id", "uuid"),
                        required("actor_summary", "varchar"),
                        required("action", "varchar"),
                        required("model_id", "varchar"),
                        required("model_revision", "varchar"),
                        required("changed_field_names", "_text"),
                        required("occurred_at", "timestamptz"),
                        required("result", "varchar"),
                        required("correlation_id", "uuid")));
        tables.put(
                "robothree_schema_version",
                List.of(
                        required("version", "int4"),
                        required("script_name", "varchar"),
                        required("script_digest", "bpchar"),
                        required("applied_at", "timestamptz"),
                        required("release_version", "varchar")));
        return Map.copyOf(tables);
    }

    private static RequiredColumn required(String name, String type) {
        return new RequiredColumn(name, type, false);
    }

    private static RequiredColumn nullable(String name, String type) {
        return new RequiredColumn(name, type, true);
    }

    record RequiredColumn(String name, String udtName, boolean nullable) {}
}
